### ISSUE TITLE
People's apps are disappearing from their webmaker profiles

### ISSUE THREAD

**Issue by simonwex** [mozilla-appmaker/appmaker#2385]
A few users have reported issues with apps disappearing from their accounts. I suspect it's a widespread problem.

See me (Simon) for accounts related to reports.

### Email 1:

> I have an account for webmaker.org for development of apps. I signed on today and suddenly the apps were missing and other apps were listed that were not mine. My account name is adamb, and the apps that were missing (that I need) were the following:

> Malaria App Final 2
> Malaria App Final

> I can see the apps under "My Makes" but cannot see them in the app maker section of the website. In fact, when I attempt to go into them and edit them, I get an "error while loading app, unable to find..." message.

> This is for a school assignment that needs to be completed tomorrow (Friday, Jan9). Please help find the missing apps.

> Thank you -

### Email 2: 

>I am emailing because I created an app that I then published to test on multiple devices.  I was always able to go back on your app builder and edit and republish my app.  Today I logged on and my app was mysteriously deleted and replaced with many example apps.  I am building my app for a science fair project and I will have a hard time recreating what was deleted.  If you could please help me to understand what happened and how I can fix it, that would be great.

### Report 3 via twitter:

https://twitter.com/ClearThinker01/status/553317795417841665

> @webmaker Just tried to sign in to make edits to an app I'd made. My apps are missing and others are in their place. What's up with that?

**Comment by fourtonfish** [comment]
Same issue here.

I happen to have one of my apps saved at https://taboo-iron-524.webmak.es/app (work in progress, the URL Navigation brick wasn't available at the time).

When I log into Appmaker, I don't have it under saved apps.

**Comment by Pomax** [comment]
Hm, concerning the report from email 1, the Appmaker mongodb instance is very much up and running, with data in it, and https://webmaker.org/search?type=all&q=malaria+final finds both projects, with the remix button taking you to the respective projects. I'm not sure there's much more I can look up with just the information from that mail. I'm not sure what "app maker section of the website" refers to (far as I know there is no tool filter anymore for makes when searching, and the apps listed in the appmaker section for remixing is a curated list, not "all apps").

**Comment by Pomax** [comment]
I can't really investigate email 2 without knowing which apps this is about (app name or its webmak.es link, etc).

**Comment by Pomax** [comment]
So, some STR to what might or might not be part of the problem, but is potentially too big to ignore: It turns out that if you use the "new app" menu option, your project will be saved to the database without an `appip`. Using "new app" and then reloading the website for a "fresh" load, yields an app that *does* have an `appid` stored in the database. The same goes for loading the website while not logged in, and then logging in so that no "previous app" gets loaded.

**Comment by ScottDowne** [comment]
I can say my personal list of apps in appmaker's "my apps" is off and some of these are not mine...

Going here however: https://webmaker.org/en-US/me shows my correct list of projects.

**Comment by Pomax** [comment]
Lots of investigation later we can report that the original problem here was the switchover to the new login, and a mismatch in the "author" field as bound in appmaker vs. the one services by the loginv3 API. That has been fixed.

This leaves us with some 50 apps that may now be orphaned, however, so we need to figure out how best to either restore these, or if we can't communicate that these still exist, but as orphans, and will need to be remixed by searching for them in the gallery and then remixing them as a new project.

**Comment by Pomax** [comment]
the bug as found in `npm`: https://github.com/npm/npm/issues/7106
