### ISSUE TITLE
Suggestions for string changes

### ISSUE THREAD

**Issue by scootergrisen** [mozilla-appmaker/appmaker#2393]
From:
"Records sounds."

To:
"Records sound."

**Comment by scootergrisen** [comment]
Should there be a question mark at the end of this string?
"How much does it cost"

**Comment by scootergrisen** [comment]
Cowbell app have this string:
"Color of the drum."

I cant see it being used so maybe it shoud be deleted or if its being used changed to:
"Color of the cowbell."

**Comment by scootergrisen** [comment]
These strings have double spaces that should be correct to only one space:
"The authoring environment (which we call the  designer) is the core of Appmaker.  Key skills we could use today are  user testing, QA, visual & interaction design, and webdev (node.js  and front-end).  The best way to find out what’s needed for the designer  is to see our Github issues labeled “good for contributors” [link]."
"We need both fixes to our existing components, and new components.  We’ll likely make a separate page to keep track of the  components that the community would like to see built, and co-design  them. If you are keen to help here, do get in touch [link] and find out what  the latest thinking is (or just make a pull request)."
"Finally, it would be very useful to give new  Appmaker users a showcase that demonstrates the breadth of possible apps and provides people with  a good starting point.  If you have introduced Appmaker to new audiences,  please share your materials[contact link], so we can make it easy for others to  find them."
"We've built some demo apps for you to try. We hope you remix them and make  them your own - it's a great way to discover what you can do with Appmaker."
"\"Mozilla  Appmaker lets you drag and drop components to easily build fun and  useful apps for your friends, your business, your classroom and your  community.\""
"Your app couldn't be published.  The server said:"

**Comment by scootergrisen** [comment]
These string all have space at the end, maybe some of them needs the space removed if not all:

"Are you sure you want to forget about the component at "

"error storing info about component: "

"Something went wrong trying to forget component for "

"There was an error checking the component at the url: "

"Successfully added component "

"Your component was not added, as Appmaker already knows "

**Comment by scootergrisen** [comment]
This string is used 9 times but "first" is suppose to change for each button:
"The first button was tapped"

**Comment by scootergrisen** [comment]
From:
"Go to previous"

To:
"Go to previous page"

So it matches with the "Go to next page" string.

**Comment by scootergrisen** [comment]
There is a string containing:
"FirefoxOS"

Should be:
"Firefox OS"

**Comment by scootergrisen** [comment]
Is guess this string is outdated:
"It's ready to try! You can author simple apps and send them to your friends. Currently, Appmaker is "Pre-Alpha" software (that means it's not even in "Beta" yet) and won't be stable until late 2014. We encourage you to have fun with Appmaker, but for now, it might not work exactly as you expect it to."

**Comment by scootergrisen** [comment]
This string have no value for the href attribute:
"Then we'd love your feedback! Fill out our short Usability Survey while <a href="">building an app</a> and we'll use your feedback to improve Appmaker."

**Comment by scootergrisen** [comment]
Change "github" to "GitHub" in this string:
**Component URL? (either full path 'http://example.com/dir/component.html' or, for github pages, 'username/repo')**

**Comment by scootergrisen** [comment]
Change "remix" to "Remix" and maybe change "Appmaker designer" to just "Appmaker" ?:
**One of the best things about Appmaker is that every app is remixable. If you find an app that someone else has made and you want to create your own version of it, you can hit the "remix" button. The app will open in the Appmaker designer, ready for you to customize.**

**Comment by scootergrisen** [comment]
"Github" to "GitHub" in this string:
"When using Github to host the component, you need to make a gh-page branch"

**Comment by scootergrisen** [comment]
Missing space before [/teach-templates]:

"If you want to mentor appmaking in your local community, we're working on educational resources on [webmaker.org] to support you. In the meantime, check out our other free tools to teach the web [/teach], or create your own appmaking tutorial using our template.[/teach-templates]"

**Comment by scootergrisen** [comment]
Missing space before "[contact link]":

Finally, it would be very useful to give new Appmaker users a showcase that demonstrates the breadth of possible apps and provides people with a good starting point. If you have introduced Appmaker to new audiences, please share your materials[contact link], so we can make it easy for others to find them.

**Comment by scootergrisen** [comment]
Change "Github" to "GitHub" and maybe there shoudl be a link instead of "[link]"?:

"The authoring environment (which we call the designer) is the core of Appmaker. Key skills we could use today are user testing, QA, visual & interaction design, and webdev (node.js and front-end). The best way to find out what’s needed for the designer is to see our Github issues labeled “good for contributors” [link]."

**Comment by scootergrisen** [comment]
The paypal component have a key called "ceci-paypal/attributes/currency" with the string "USD" on Transifex.

Maybe there should be a comment if the USD should be the same or translated to the local currency.

**Comment by scootergrisen** [comment]
Maybe change:
"Unsaved App"
To:
"Untitled App"

**Comment by Pomax** [comment]
in preparation for sunsetting Appmaker, as per https://github.com/mozilla-appmaker/appmaker/issues/2409, this issue will be closed.
