### ISSUE TITLE
White text on white background in component Audio Clip

### ISSUE THREAD

**Issue by scootergrisen** [mozilla-appmaker/appmaker#2406]
For some reason the text color for label class is white.
Also the background is white.
So i cant see the text unless i double click to select the text.

    <div class="label">
        <div class="text">Play</div>
    </div>

**Comment by Pomax** [comment]
in preparation for sunsetting Appmaker, as per https://github.com/mozilla-appmaker/appmaker/issues/2409, this issue will be closed.
