### ISSUE TITLE
Nothing happens when trying to add Voice Recognition

### ISSUE THREAD

**Issue by scootergrisen** [mozilla-appmaker/appmaker#2407]
When i click to add Voice Recognition nothing happens.
Console says "Your browser do not support the Web Speech API".
Also the thumbnail is not found. 404.

Maybe there should be some kind of message for the user i case the users browser does not support Your browser do not support Web Speech API so the user understand why it is not added.

**Comment by Pomax** [comment]
in preparation for sunsetting Appmaker, as per https://github.com/mozilla-appmaker/appmaker/issues/2409, this issue will be closed.
