### ISSUE TITLE
Buttons in component Double Button disappear on click

### ISSUE THREAD

**Issue by scootergrisen** [mozilla-appmaker/appmaker#2408]
If i add component Double Button and click the buttons they disappear.

Maybe they become white or transparent.

If i hold the mouse button pressed the button appear but disappear again when i release the mouse button.

**Comment by Pomax** [comment]
in preparation for sunsetting Appmaker, as per https://github.com/mozilla-appmaker/appmaker/issues/2409, this issue will be closed.
