### ISSUE TITLE
Show a banner describing the future of Appmaker

### ISSUE THREAD

**Issue by secretrobotron** [mozilla-appmaker/appmaker#2412]
We should have a banner on Appmaker which describes what's happening to the tool and the makes (probably just a link to https://blog.webmaker.org/whats-next-for-webmaker-tools).

Something like...
```
<div style="z-index: 9999; position: absolute; top: 0; left: 0; right: 0; height: 2em; background-color: red; color: white; text-align: center; padding-top: 0.25em;">
  <div style="position: absolute; right: 0; height: 100%; width: 50px; cursor: pointer;" onclick="this.parentNode.parentNode.removeChild(this.parentNode)">X</div>
  Hey! Webmaker is changing, and Appmaker will be put on ice indefinitely.
  <a href="https://blog.webmaker.org/whats-next-for-webmaker-tools" style="color: white;">Check it.</a>
</div>
```

![screenshot 2015-06-03 16 41 12](https://cloud.githubusercontent.com/assets/403231/7970943/610b9e04-0a0f-11e5-89e3-3b8f83fffd29.png)

Blocks #2409

**Comment by secretrobotron** [comment]
* What should the message say?
* Can we get @vazquez to suggest a good colour?

**Comment by simonwex** [comment]
May I suggest it doesn't overlay, but instead shifts the app down?

**Comment by secretrobotron** [comment]
:+1: good idea

**Comment by errietta** [comment]
@secretrobotron  please see https://github.com/mozilla-appmaker/appmaker/pull/2413

2 things:
1: For some reason I failed to 'properly' add an evt listener to the close button (document.getElementById('..').addEventListener, etc.) if you want you can help me figure out what went wrong
2: After closing the warning, when scrolling now, you can see a different-coloured area at the top...

**Comment by secretrobotron** [comment]
For the close button, I think what you have there is fine.

Maybe instead of changing those `top` properties directly, add a class to things that you want stepped down. Then, if the user presses the close button, just remove the class. That work?

**Comment by secretrobotron** [comment]
And we'll have to change that June 19 date, obviously (cc @hpauljohnson).

**Comment by secretrobotron** [comment]
@simonwex what's a good date to use here, if any?

**Comment by secretrobotron** [comment]
@davidascher ^^ ? What do you think?

**Comment by secretrobotron** [comment]
Thanks @errietta :sheep:
